baseurl = "http://localhost:1313/"
title = "Pentest Report"
languageCode = "en-us"
theme = "arsenic"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

paginate  = 0
rssLimit  = 0  # Maximum number of items in the RSS feed.
[menu]
  [[menu.main]]
    identifier = "findings"
    name       = "Findings"
    url        = "findings/"
  [[menu.main]]
    identifier = "hosts"
    name       = "Hosts"
    url        = "hosts/"
  [[menu.main]]
    identifier = "TCPPorts"
    name       = "TCPPorts"
    url        = "tcpports/"
  [[menu.main]]
    identifier = "UDPPorts"
    name       = "UDPPorts"
    url        = "udpports/"
  [[menu.main]]
    identifier = "hostnames"
    name       = "Hostnames"
    url        = "hostnames/"
  [[menu.main]]
    identifier = "rootdomains"
    name       = "Root Domains"
    url        = "rootdomains/"
  [[menu.main]]
    identifier = "flags"
    name       = "Flags"
    url        = "flags/"
  [[menu.main]]
    identifier = "pipeline"
    name       = "Pipeline"
    url        = "pipeline/"

[taxonomies]
    Port = "Ports"
    Flag = "Flags"
    Hostname = "Hostnames"
    RootDomains = "RootDomains"
    Reviewer = "Reviewer"
    TCPPorts = "TCPPorts"
    UDPPorts = "UDPPorts"
#
# Personalization params
#
[params]

    # optionally specify where the content is
    findingSections = ["findings"]
    hostSections = ["hosts"]

    # theme's color scheme
    first_color="#f8f8f8"
    first_border_color="#e7e7e7"
    first_text_color="#333"

    second_color="white"
    second_text_color="#333"

    header_color="#f8f8f8"
    header_text_color="rgb(51, 51, 51)"

    header_link_color="#777"
    header_link_hover_color="rgb(51, 51, 51)"

[[params.reportSections]]
  label = "Scope"
  file = "scope"

[[params.reportSections]]
  label = "Foreword"
  file = "foreword"

[[params.reportSections]]
  label = "Executive Summary"
  file = "executive_summary"

[[params.reportSections]]
  label = "Attack Narrative"
  file = "attack_narrative"

[[params.reportSections]]
  label = "Strengths and Weaknesses"
  file = "strengths_and_weaknesses"

[[params.reportSections]]
  label = "Recommendations"
  file = "recommendations"

#
# Adjust privacy settings
# See: https://gohugo.io/about/hugo-and-gdpr/
#
[privacy]
    [privacy.disqus]
      disable = true

    [privacy.googleAnalytics]
      disable = true
      anonymizeIP = true
      respectDoNotTrack = true
      useSessionStorage = true

    [privacy.instagram]
      disable = true
      simple = true

    [privacy.twitter]
      disable = true
      enableDNT = true
      simple = true

    [privacy.vimeo]
      disable = true
      simple = true

    [privacy.youtube]
      disable = true
      privacyEnhanced = true

#
# In simple mode for Instagram and a site styled with Bootstrap 4,
# you may want to disable the inlines styles provided by Hugo:
# See: https://gohugo.io/about/hugo-and-gdpr/
#
[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
